
GET http://localhost:3333

#####
POST http://localhost:3333/api/user HTTP/1.1
Content-Type: application/json

{
  "name":"igor",
  "email": "john@gmail.com",
  "password": "12345678"
}
####

POST http://localhost:3333/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "12345678"
}

### create - notes 

//e2c82880-fb4c-4a2d-a8f6-2bcd25cb02b5

POST http://localhost:3333/notes HTTP/1.1
Content-Type: application/json

{
  "userId": "e2c82880-fb4c-4a2d-a8f6-2bcd25cb02b5",
  "title": "Boniteza",
  "content": "Eu preciso ser mais bonito"
}

###

GET http://localhost:3333/notes/2f545f57-e4c5-4818-9901-69bd2ec13493



